[package]
name = "qrcode-encoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["cargo"] }
image = "0.24.9"
qrcode = "0.13.0"
